const AUTH_TOKEN = 'AUTH_TOKEN';
const USER_ID = `USER_ID`;

const QuestionTypes = {
  SCALE: `SCALE`,
  TEXT: `TEXT`,
  OPTIONS: `OPTIONS`,
  WOULD_YOU_SINGLE: `WOULD_YOU_SINGLE`,
  WOULD_YOU_DOUBLE: `WOULD_YOU_DOUBLE`,
};

export { AUTH_TOKEN, USER_ID, QuestionTypes };
